# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: can.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='can.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\tcan.proto\"\xb9\x01\n\x07\x46rameU8\x12\x14\n\x0c\x66ield_name_1\x18\x01 \x01(\t\x12\x14\n\x0c\x66ield_name_2\x18\x02 \x01(\t\x12\x14\n\x0c\x66ield_name_3\x18\x03 \x01(\t\x12\x14\n\x0c\x66ield_name_4\x18\x04 \x01(\t\x12\x14\n\x0c\x66ield_name_5\x18\x05 \x01(\t\x12\x14\n\x0c\x66ield_name_6\x18\x06 \x01(\t\x12\x14\n\x0c\x66ield_name_7\x18\x07 \x01(\t\x12\x14\n\x0c\x66ield_name_8\x18\x08 \x01(\t\"b\n\x08\x46rameU16\x12\x14\n\x0c\x66ield_name_1\x18\x01 \x01(\t\x12\x14\n\x0c\x66ield_name_2\x18\x02 \x01(\t\x12\x14\n\x0c\x66ield_name_3\x18\x03 \x01(\t\x12\x14\n\x0c\x66ield_name_4\x18\x04 \x01(\t\"R\n\x07\x43\x61nData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x04\x12\x16\n\x02u8\x18\x02 \x01(\x0b\x32\x08.FrameU8H\x00\x12\x18\n\x03u16\x18\x03 \x01(\x0b\x32\t.FrameU16H\x00\x42\x07\n\x05\x66rame\"{\n\x06\x43\x61nMsg\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1e\n\x06source\x18\x02 \x01(\x0e\x32\x0e.CanMsg.Source\x12\x1a\n\x08\x63\x61n_data\x18\x03 \x01(\x0b\x32\x08.CanData\x12\x10\n\x08msg_name\x18\x04 \x01(\t\"\x17\n\x06Source\x12\r\n\tTELEMETRY\x10\x00\"!\n\tCanSchema\x12\x14\n\x03msg\x18\x01 \x03(\x0b\x32\x07.CanMsgb\x06proto3')
)



_CANMSG_SOURCE = _descriptor.EnumDescriptor(
  name='Source',
  full_name='CanMsg.Source',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TELEMETRY', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=485,
  serialized_end=508,
)
_sym_db.RegisterEnumDescriptor(_CANMSG_SOURCE)


_FRAMEU8 = _descriptor.Descriptor(
  name='FrameU8',
  full_name='FrameU8',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field_name_1', full_name='FrameU8.field_name_1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_name_2', full_name='FrameU8.field_name_2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_name_3', full_name='FrameU8.field_name_3', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_name_4', full_name='FrameU8.field_name_4', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_name_5', full_name='FrameU8.field_name_5', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_name_6', full_name='FrameU8.field_name_6', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_name_7', full_name='FrameU8.field_name_7', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_name_8', full_name='FrameU8.field_name_8', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=199,
)


_FRAMEU16 = _descriptor.Descriptor(
  name='FrameU16',
  full_name='FrameU16',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field_name_1', full_name='FrameU16.field_name_1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_name_2', full_name='FrameU16.field_name_2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_name_3', full_name='FrameU16.field_name_3', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_name_4', full_name='FrameU16.field_name_4', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=299,
)


_CANDATA = _descriptor.Descriptor(
  name='CanData',
  full_name='CanData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='CanData.data', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='u8', full_name='CanData.u8', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='u16', full_name='CanData.u16', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='frame', full_name='CanData.frame',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=301,
  serialized_end=383,
)


_CANMSG = _descriptor.Descriptor(
  name='CanMsg',
  full_name='CanMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CanMsg.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='CanMsg.source', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='can_data', full_name='CanMsg.can_data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_name', full_name='CanMsg.msg_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CANMSG_SOURCE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=508,
)


_CANSCHEMA = _descriptor.Descriptor(
  name='CanSchema',
  full_name='CanSchema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='CanSchema.msg', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=510,
  serialized_end=543,
)

_CANDATA.fields_by_name['u8'].message_type = _FRAMEU8
_CANDATA.fields_by_name['u16'].message_type = _FRAMEU16
_CANDATA.oneofs_by_name['frame'].fields.append(
  _CANDATA.fields_by_name['u8'])
_CANDATA.fields_by_name['u8'].containing_oneof = _CANDATA.oneofs_by_name['frame']
_CANDATA.oneofs_by_name['frame'].fields.append(
  _CANDATA.fields_by_name['u16'])
_CANDATA.fields_by_name['u16'].containing_oneof = _CANDATA.oneofs_by_name['frame']
_CANMSG.fields_by_name['source'].enum_type = _CANMSG_SOURCE
_CANMSG.fields_by_name['can_data'].message_type = _CANDATA
_CANMSG_SOURCE.containing_type = _CANMSG
_CANSCHEMA.fields_by_name['msg'].message_type = _CANMSG
DESCRIPTOR.message_types_by_name['FrameU8'] = _FRAMEU8
DESCRIPTOR.message_types_by_name['FrameU16'] = _FRAMEU16
DESCRIPTOR.message_types_by_name['CanData'] = _CANDATA
DESCRIPTOR.message_types_by_name['CanMsg'] = _CANMSG
DESCRIPTOR.message_types_by_name['CanSchema'] = _CANSCHEMA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FrameU8 = _reflection.GeneratedProtocolMessageType('FrameU8', (_message.Message,), dict(
  DESCRIPTOR = _FRAMEU8,
  __module__ = 'can_pb2'
  # @@protoc_insertion_point(class_scope:FrameU8)
  ))
_sym_db.RegisterMessage(FrameU8)

FrameU16 = _reflection.GeneratedProtocolMessageType('FrameU16', (_message.Message,), dict(
  DESCRIPTOR = _FRAMEU16,
  __module__ = 'can_pb2'
  # @@protoc_insertion_point(class_scope:FrameU16)
  ))
_sym_db.RegisterMessage(FrameU16)

CanData = _reflection.GeneratedProtocolMessageType('CanData', (_message.Message,), dict(
  DESCRIPTOR = _CANDATA,
  __module__ = 'can_pb2'
  # @@protoc_insertion_point(class_scope:CanData)
  ))
_sym_db.RegisterMessage(CanData)

CanMsg = _reflection.GeneratedProtocolMessageType('CanMsg', (_message.Message,), dict(
  DESCRIPTOR = _CANMSG,
  __module__ = 'can_pb2'
  # @@protoc_insertion_point(class_scope:CanMsg)
  ))
_sym_db.RegisterMessage(CanMsg)

CanSchema = _reflection.GeneratedProtocolMessageType('CanSchema', (_message.Message,), dict(
  DESCRIPTOR = _CANSCHEMA,
  __module__ = 'can_pb2'
  # @@protoc_insertion_point(class_scope:CanSchema)
  ))
_sym_db.RegisterMessage(CanSchema)


# @@protoc_insertion_point(module_scope)
